### PR TITLE
fix: Optimizations

### PR DESCRIPTION
**Pull request by aminya**
This applies some optimizations to the code.

The speed bottleneck is in the highlight-selected package itself. I will need to send a PR to that package.

### CODE REVIEW

**Comment by UziTech** [comment]
What is with the big-files.zip

I don't think we need every person downloading an extra 26kb file if it isn't even being used.

**Comment by aminya** [comment]
I don't mind removing it. However, 26KB to me is like nothing. Even on 2G, it takes 1 second to download.

> If it is for a script can we have it be downloaded for the test instead of including in the bundle?

`download` dependency is 86 KB, which is 4 times more than the size of the zipped file.
https://bundlephobia.com/result?p=download@8.0.0

Downloading makes sense when the file is really huge. Like this:
https://github.com/aminya/superstring/blob/13ef1e3461ad06c6526249f1025dcfdcb76157e2/benchmark/large-text-buffer.benchmark.js#L13-L19

**Comment by UziTech** [comment]
still it seems like it isn't used anywhere. Why do we need it?

**Comment by aminya** [comment]
> still it seems like it isn't used anywhere. Why do we need it?

Yes, I did not write code for benchmarking. I just used the big file with some `performance.now` to do this. As I said, I am OK with reverting the commit if it seems redundant.

**Comment by UziTech** [comment]
Ya I don't think we need it on every minimap package unless there is actually a test that uses it.

**Comment by UziTech** [comment]
we could add it to .gitignore and you can keep it there for tests if you want.

**Comment by aminya** [comment]
> Ya I don't think we need it on every minimap package unless there is actually a test that uses it.

I have reverted the commits. I will keep a local copy instead.

**Pull request merged**
