### PR TITLE
Use basic API from Highlight Selected

### PR DESCRIPTION
**Pull request by richrace**
Requires https://github.com/richrace/highlight-selected/pull/81

### CODE REVIEW

**Comment by richrace** [comment]
Hi @abe33, had a go at making an API. What do you think? A lot less code :smile:

**Comment by abe33** [comment]
Thank you for taking care of that :bow:, I'll review this PR as soon as I'm back home tonight.

**Comment by richrace** [comment]
I think I need to add an event in `highlight-selected` when markers are removed. As whilst the markers and their decorations are destroyed. I'm not sure if the array that stores them in this plugin will stay.

**Comment by richrace** [comment]
Sweet. I'll let you know when I merge the API on my side :smile: I'm not near my computer at the mo.

**Comment by abe33** [comment]
Yup, it needed some rewrite, but it's working nice. I'll now just need to take care of the hidden markers when they're selected.
You can to deploy a service without anyone using it yet, you didn't had to wait for me ;).

**Comment by abe33** [comment]
Hmm actually, I forgot I was overriding how your view worked in order to display the markers even when the `hideHighlightOnSelectedWord` setting is true, as does ST. I'm not sure how I can do that only my side. Do you have any idea about that feature?

**Pull request merged**
